# Generated by Django 4.0.4 on 2022-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Mi Increible y Maldito Blog', max_length=255),
        ),
    ]
